apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: echo-env
namespace: echo-env
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
